#!/bin/bash
# Power menu, rendered with rofi so the palette lives only in rofi/config.rasi
# instead of 16 hand-passed bemenu colour flags. Icons are fed through rofi's
# dmenu icon protocol (LABEL\0icon\x1fICON) so they render in the element-icon
# slot -- the same path the app launcher uses -- instead of Nerd Font glyphs
# embedded in the label text, which sat inside the row and looked indented.
#
# Icons are ABSOLUTE PATHS to palette-coloured SVGs generated by wallust
# (see wallust/templates/icons/), not freedesktop icon names. Previously these
# were names resolved via the Papirus theme, which meant e.g.
# /usr/share/icons/Papirus/24x24/apps/system-shutdown.svg -- a Material red
# (#f44336) glyph with no relation to the cyberpunk palette. Regenerate them
# with ~/.config/wallust/theme-switch; they follow the active theme.
#
# Destructive actions require a confirmation pick.

set -euo pipefail

ICONS="$HOME/.config/rofi/icons"

menu() {
    # $1 = prompt. Entries arrive on stdin as rofi icon rows (NUL/US separated).
    rofi -dmenu -i -p "$1" -theme-str 'listview { lines: 6; } window { width: 20%; }'
}

confirm() {
    # Returns success only if the user explicitly picks "Yes".
    local answer
    answer=$(printf '%s\0icon\x1f%s\n' \
        'Yes' "$ICONS/yes.svg" \
        'No'  "$ICONS/no.svg" | menu "$1")
    [[ "$answer" == Yes ]]
}

CHOICE=$(printf '%s\0icon\x1f%s\n' \
    'Lock'      "$ICONS/lock.svg" \
    'Suspend'   "$ICONS/suspend.svg" \
    'Logout'    "$ICONS/logout.svg" \
    'Hibernate' "$ICONS/hibernate.svg" \
    'Restart'   "$ICONS/reboot.svg" \
    'Shutdown'  "$ICONS/shutdown.svg" | menu 'Power')

case "$CHOICE" in
    Lock)      hyprlock ;;
    Suspend)   systemctl suspend ;;
    Logout)    confirm 'Log out?'   && hyprctl dispatch exit ;;
    Hibernate) confirm 'Hibernate?' && systemctl hibernate ;;
    Restart)   confirm 'Reboot?'    && systemctl reboot ;;
    Shutdown)  confirm 'Shut down?' && systemctl poweroff ;;
esac
