splash = false
ipc = true

preload = /home/edargham/Pictures/Wallpapers/Cyberpunk-3.jpeg
preload = /home/edargham/Pictures/Wallpapers/Cyberpunk-2.jpg

wallpaper {
    monitor = DP-1
    path = /home/edargham/Pictures/Wallpapers/Cyberpunk-3.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/edargham/Pictures/Wallpapers/Cyberpunk-2.jpg
    fit_mode = cover
}
