# Cyberpunk Theme (Modified from Gruvbox Dark Hard)
# Theme create by: https://github.com/frost-phoenix
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "monokai"

# ========= Border =========
file_panel_border = "#5de5ff"
sidebar_border = "#666666"
footer_border = "#666666"

# ========= Border Active =========
file_panel_border_active = "#5de5ff"
sidebar_border_active = "#5de5ff"
footer_border_active = "#c7f5ff"
modal_border_active = "#5de5ff"

# ========= Background (bg) =========
full_screen_bg = "#333333"
file_panel_bg = "#333333"
sidebar_bg = "#333333"
footer_bg = "#333333"
modal_bg = "#333333"

# ========= Foreground (fg) =========
full_screen_fg = "#5de5ff"
file_panel_fg = "#5de5ff"
sidebar_fg = "#5de5ff"
footer_fg = "#5de5ff"
modal_fg = "#5de5ff"

# ========= Special Color =========
cursor = "#5de5ff"
correct = "#c7f5ff"
error = "#d946ef"
hint = "#5de5ff"
cancel = "#666666"
# Gradient color can only have two color!
gradient_color = ["#d946ef", "#c7f5ff"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#5de5ff"
file_panel_top_path = "#5de5ff"
file_panel_item_selected_fg = "#c7f5ff"
file_panel_item_selected_bg = "#1A1A1A"

# ========= Sidebar Special Items =========
sidebar_title = "#d946ef"
sidebar_item_selected_fg = "#c7f5ff"
sidebar_item_selected_bg = "#1A1A1A"
sidebar_divider = "#666666"

# ========= Modal Special Items =========
modal_cancel_fg = "#d946ef"
modal_cancel_bg = ""

modal_confirm_fg = "#c7f5ff"
modal_confirm_bg = ""

# ========= Help Menu =========
help_menu_hotkey = "#5de5ff"
help_menu_title = "#d946ef"
